name: "build-release"

on:
  push:
    branches:
      - "master"

jobs:
  build-release:
    name: "Build & Release"
    runs-on: "windows-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          submodules: true
      # ...
      - name: "Build Yakuza 0"
        run: |
          cargo.exe build --bin yakuza0-freecam --release

      - name: "Build Yakuza Kiwami"
        run: |
          cargo.exe build --bin kiwami-freecam --features kiwami --release

      - name: "Build Yakuza Kiwami 2"
        run: |
          cargo.exe build --bin kiwami2-freecam --features kiwami2 --release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest release"
          files: |
            **.exe

