name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          cargo.exe build --bin yakuza0-freecam --release
          cargo.exe build --bin kiwami-freecam --features kiwami --release
          cargo.exe build --bin kiwami2-freecam --features kiwami2 --release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest release"
          files: |
            **.exe
